### ISSUE TITLE
Add to Grape projects

### ISSUE THREAD

**Issue by dblock** [wawandco/grape-resources#16]
Add to https://github.com/ruby-grape/ruby-grape.github.io/blob/master/projects/index.md, please!

**Comment by paganotoni** [comment]
@dblock i think this one can be closed, thanks!

**Comment by kuldeepaggarwal** [comment]
@apaganobeleno: Are all these functionalities present already in the gem?

**Comment by paganotoni** [comment]
@kuldeepaggarwal all that we mention in our Readme.md
